### PR TITLE
Another version of the tool in Python

### PR DESCRIPTION
**Pull request by frankenstein91**
This version is currently intended for Archlinux. The data output is in XML format. It does not use the home folder of the user. it is working in tmpfiles. 
Another function is the transmission of a checksum to the Tuxedo server.
Some changes from @StevenSeifried are already included.

The following information is collected:

- Linux Distro
- Installed Software
- Linux Kernel
- DKMS
- PKGManager config and repos
- System boottime
- AC Power and battery info
- Network card information (no IP)
- Disk mounts (works with btrfs)
- PCI devs
- USB devs
- MotherBoard and bios information
- CPU and RAM info

### CODE REVIEW

**Comment by frankenstein91** [comment]
Do you need more information?

**Comment by frankenstein91** [comment]
Is there something wrong with this request? Can I improve something?

**Comment by vinzv** [comment]
Hi,

first of all: thanks for your efforts, we really appreciate it!

There's nothing wrong with your request but I can't see the advantage of a version written in Python over the existing Bash one. Furthermore with Bash it's easier to enhance as we don't need throw developer's working time at it. Even I myself can tinker with Bash. ;-) 
So I'd propose to keep the Python variant in separate repository and maybe we can place a link to it in the readme of this one.

**Comment by frankenstein91** [comment]
Hi,
cool to hear from you. So far, it hasn't been much of an effort. I think the copy of my script has some more information. But I get the Bash argument. I just get along much better with Python than with Bash scripts. I'm the opposite of you... ...when I'm writing a Bash script, I always think, "What does that want from me right now?" 
But now that we've closed the pull request, I can move on to the other Linux versions.

When we set a link, I hope the support is able to handle XML. Are you having second thoughts?

**Pull request closed without merging**
